import log

__author__ = 'cvw'

def main():
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    http://projecteuler.net/problem=2
    """
    log.header("Euler Problem 2")
    sum = 0
    fibonacciPrevious = 1
    fibonacci = 2
    fibonacciMax = 4000000
    while fibonacci < fibonacciMax:
        message = "fibonacci:%s"%fibonacci
        if fibonacci % 2 == 0:
            sum += fibonacci
            message += "|  adding to sum"
        log.debug(message)
        fibonacciTmp = fibonacci
        fibonacci += fibonacciPrevious
        fibonacciPrevious = fibonacciTmp

    print(sum)

main()
